### ISSUE TITLE
Broken in Oracle VirtualBox

### ISSUE THREAD

**Issue by abimagnus** [WernerFP/Shades-of-gray-theme#10]
Seems to be the theme is broken in Oracle Virtual Box v6.0..!
![virtual](https://user-images.githubusercontent.com/8939183/63654131-b3130980-c793-11e9-82b4-f483b41685a7.png)

**Comment by WernerFP** [comment]
Yes, it is a bug in VirtualBox 6.0. Shades-of-gray theme folders contain the file `Shades-of-gray-Readme.html` with the description of a workaround. Text snippet:

### VirtualBox 6.0: GTK issue

The main window in VirtualBox 6.0 (Qt5) is not readable with dark gtk-themes via `*qt5ct*` (white font on light background).

You can work around this improper conduct by starting VirtualBox with qt5-theme '*Fusion*' instead of the gtk-theme:
```
VirtualBox -style Fusion
```
... or by editing the VirtualBox launcher:

```
- Exec=VirtualBox %U
+ Exec=VirtualBox -style Fusion %U
```

**Comment by abimagnus** [comment]
OKay Thank You !
