### ISSUE TITLE
Firefox text selection color doesn't follow the .css

### ISSUE THREAD

**Issue by mikeldavis** [WernerFP/Shades-of-gray-theme#9]
Just upgraded to Firefox 68 and noticed that when I highlight text on a webpage to copy/paste, it is the Firefox blue instead of the Shades of Gray-patina as before. I have downloaded the new userChrome.css and userContent.css from the Shades of Gray-Patina folder, app-gadgets, Firefox Shades of gray subfolder. Is there some way to get the highlight color in Firefox to match the color from the theme as it did prior to the upgrade?

**Comment by mikeldavis** [comment]
I'm going to use the old userContent.css for now with this tacked on to the end:

*::selection {
  /* This is the background color */
  background: #3c7460 !important;
  /* This is the text color */
color: #FFFFFF !important}

**Comment by WernerFP** [comment]
The `::selection` CSS pseudo-element applies colors to parts of documents that has been selected. Your CSS instruction in `userContent.css` is the right way to do this.

But there are undesirable side effects. For example, some web pages set the background color of selected text and keep the text color: [code block example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Shorter_functions) - your`::selection` instruction results in white text with light blue background.

You may as well add your instruction to the current version of `userContent.css` (1.1.8). I recommend that because there have been major changes to the Firefox form widgets and the new design of QuantumBar address and search bar, starting with Firefox 68.

I'm wondering: such an instruction was not contained in previous releases of `userContent.css` and I can't reproduce the issue you described. Or do you specifically mean the selection color in input fields?

**Comment by mikeldavis** [comment]
I'm sure you're not mistaken. I had the functionality as described, when highlighting text to copy/paste from Firefox it was the patina green color, and assumed that it came from userContent.css. But I also use some Firefox addons like Stylish and Firefox Color, so it must have come from one of those instead. I am so sorry! Thanks for your time, patience, and for maintaining this great theme.

**Comment by WernerFP** [comment]
You're welcome!
